new workflow token

diff --git a/.github/workflows/azure-static-web-apps-green-sand-043e3830f.yml b/.github/workflows/azure-static-web-apps-green-sand-043e3830f.yml
--- a/.github/workflows/azure-static-web-apps-green-sand-043e3830f.yml
+++ b/.github/workflows/azure-static-web-apps-green-sand-043e3830f.yml
@@ -39,15 +39,15 @@ jobs:
 
       - name: Verify SWA token exists
         run: |
-          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_SAND_043E3830F }}" ]; then
-            echo "Missing AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_SAND_043E3830F"; exit 1;
+          if [ -z "${{ secrets.SWA_DEPLOYMENT_TOKEN }}" ]; then
+            echo "Missing SWA_DEPLOYMENT_TOKEN"; exit 1;
           fi
 
       - name: Build and Deploy
         id: builddeploy
         uses: Azure/static-web-apps-deploy@v1
         with:
-          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_SAND_043E3830F }}
+          azure_static_web_apps_api_token: ${{ secrets.SWA_DEPLOYMENT_TOKEN }}
           action: "upload"
           app_location: "/"
           api_location: ""
@@ -62,7 +62,7 @@ jobs:
         id: closepullrequest
         uses: Azure/static-web-apps-deploy@v1
         with:
-          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_SAND_043E3830F }}
+          azure_static_web_apps_api_token: ${{ secrets.SWA_DEPLOYMENT_TOKEN }}
           action: "close"
           app_location: "/"
           api_location: ""
